version: 2
jobs:
  build:
    working_directory: ~/portfolio
    docker:
      - image: circleci/node:7.9
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run lint
      - run: npm run lint:css

  deploy:
    working_directory: ~/portfolio
    docker:
      - image: circleci/node:7.9
    steps:
      - restore_cache:
          key: deps-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2
  deploy:
    jobs:
      - build
      - deploy:
        requires:
          - build
        filters:
          branches:
            only: master